version: 2.1
jobs:
  build:
    working_directory: ~/microserver-comments/microserver-nest
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: ls -l
#      - run: npm install
#      - run:
#          working_directory: ~/microserver-comments/microserver-nest
#          command: npm install
